apiVersion: v1
kind: ConfigMap
metadata:
  name: pychatgpt-etc
  namespace: pychatgpt
data:
  pychatgpt.conf: |+
    [chatgpt]
    session_token = {token}

    [tls_client]
    http_proxy = {proxy}
    https_proxy = {proxy}

    [chrome]
    driver_exec_path =
    browser_exec_path =

    [hook]
    url = ws://192.168.5.136:5555